project: ""

mbelt:
  repository: altvnv/mbelt_preloader
  tag: 77bc8650

rabbitmq:
  username: "mblet"
  password: "rabbitmqpassword"

database:
  username: "mbelt"
  password: "pgpassword"

authorizedNetworks:
  - name: "all"
    address: "0.0.0.0/0"

polkadotWSRPCUrl: "wss://rpc.polkadot.io/"

airflow:
  username: admin
  password: "airflowpassword"
  fernetKey: ""
  webserverKey: ""

superset:
  username: admin
  password: "supersetpassword"
  secretKey: ""
